* blog
** [[http://www.matrix67.com/blog/][Matrix67: The Aha Moments]]
** http://www.clyce.net/
** [[http://evi1cg.me/][一个黑客技术的blog]]
** [[http://zhan.renren.com/linuxzhouxin][Linux门徒]]
   投身Linux的海洋，拥抱真正的IT技术，使自己成为一段BOSS代码！
** [[http://calvin1978.blogcn.com/][花钱的年华]]
* [[http://www.iteye.com/topic/770032][mysql链接url中的rewriteBatchedStatements参数]]
* great fire wall
** twister
   http://twisterio.com
   
   http://twister.net.co/
** just proxy (chrome plugin)
   http://goo.gl/0qEKSs
** http://www.dou-bi.com/
** http://fanqianghou.com/
   or
   https://s3.amazonaws.com/fanqianghou/index.html
** aixyz
** [[http://www.aboutyun.com/thread-11395-1-1.html][让你真正明白Linux NTP（包括历史、参数解释、安装配置）]]
* 镜像
** http://maven.aliyun.com/nexus/content/groups/public/
** https://mirrors.tuna.tsinghua.edu.cn/
** http://mirrors.aliyun.com/
** http://www.opencas.org/mirrors/
** http://mirrors.neusoft.edu.cn/
** [[https://www.douban.com/note/517555410/][其他]]

* 六爻相关
** [[http://www.360doc.com/content/15/0620/23/25024905_479486344.shtml][六十四卦世应六亲简单记忆法]]
   第一首先记口诀：

   天同二世天变五，地同四世地变初，人同游魂（四爻）人变归（三爻）。

   一二三六外卦宫，四五游魂内变更，归魂内卦是本宫。

   讲解：六十四卦有外卦与内卦，外卦与内卦都有天爻，地爻，人爻。天同（天爻同其它两爻不同）二爻是世爻；天变（天爻不同其它两爻同）五爻是世爻；地同（地爻同其它两爻不同）四爻是世爻；地变（地爻不同其它两爻同）初爻是世爻；人同（人爻同其它两爻不同）是游魂卦，世爻在四爻；人变（人爻不同其它两爻同）是归魂卦，世爻在三爻。

   下边这个口诀说的就是按六亲，但是首先得找出兄弟爻，一二三六（世爻在一二三六爻的）外卦的五行就是兄弟（如乾卦金爻就是兄弟）；四五和游魂卦内卦的变爻就是兄弟爻（如内卦是乾卦，乾卦三爻全变就是坤卦）；归魂卦的内卦就是兄弟爻（如内卦是乾卦，金爻就是兄弟爻）。

   第二给六十四卦按地支：

   得记住：首先是阳卦，乾（父亲）和震（老大）的内外卦一样，从下向上为（都是阳地支）：子水；寅木；辰土；（内卦）午火；申金；戌土（外卦）。坎（老二）的内外卦，从下向上为：寅木；辰土；午火（内卦）；申金；戌土；子水（外卦）。艮（老三）的内外卦为：辰土；午火；申金（内卦）；戌土；子水；寅木（外卦）。

   上头我说的都是阳卦，地支要用阳地支子，寅，辰，午，申，戌。子（子为阳爻第一爻）开头放到乾（父亲）和震（老大）的初爻，其次再二爻寅，三爻辰依次为四午五申六戌爻；寅（阳爻第二爻）放到坎（老二）的初爻，依次论推；辰（阳爻第三爻）放到艮（老三）的初爻，依次论推。

   其次是阴卦，按阴地支逆数，丑，亥，酉，未，巳，卯。巽大女儿，第一爻丑爻，二爻亥，三爻酉，四爻未，五爻巳，上爻卯。其次离二女儿，第一爻卯，依次是丑，亥，酉，未，巳。其次是兑三女儿，第一爻是巳，依次是卯，丑，亥，酉，未。其次是坤母亲，第一爻是未，依次是巳，卯，丑，亥，酉，未。你记住它们的第一爻从大女儿，二女儿，三女儿，母亲分别是，丑，卯，巳，未，有第一爻其它爻从下向上逆数，我一直这样用，也很好用，现在奉献给大家，希望对大家有点用。

* 不知道的东西
** webm,vp8
** AA|BB|CC|DD|DD|EE|FF 要替换第5个|后边的内容 sed 's/[^|]\+/YY/5'

   [[http://zhidao.baidu.com/link?url=nXsZA29OwN0-OHVPTqpeQEjDQYuabbg-pFbgT8GfY_5_yBq4IGcgh7MvzKxtzjUJjHQSbkMmebh4LWlfms4Faq][baidu]]
** Data URI scheme
   Data URI scheme是在RFC2397中定义的
** hash
   *MurmurHash* 是一种非加密型哈希函数，适用于一般的哈希检索操作。由Austin Appleby在2008年发明，并出现了多个变种，都已经发布到了公有领域(public domain)。与其它流行的哈希函数相比，对于规律性较强的key，MurmurHash的随机分布特征表现更良好。

   *Merkle Damgard*
** p2p
** 药
*** 广东凉茶
    配料：葡萄糖、鲜芦根、夏枯草、布渣叶、鸡蛋花、仙草、菊花。
*** 通窍鼻炎颗粒
    + 成分：苍耳子（炒）、防风、黄芪、白芷、辛夷、白术（炒）、薄荷。
    + 功能主治：散风消炎，宣通鼻窍。用于鼻渊，鼻塞，流涕，前额头痛；鼻炎，鼻窦炎及过敏性鼻炎。
** [[http://www.360doc.com/content/14/0508/09/10886293_375705590.shtml][榫卯:中国传统家具的灵魂结构]]
** 六十甲子可能和北斗星有关
   * 大挠“采五行之情，占斗机所建，始作甲乙以名日，谓之干；作子丑以名月，谓之枝，有事于天则用日，有事于地则用月，阴阳之别，故有枝干名也。”
   * 《竹书纪年》首句云：“黄帝轩辕氏，母曰附宝，见大电绕北斗枢星，光照郊野,感而孕。二十五月而生帝于寿丘。”（63）
   * 《史拾·广览·河图始开图》云：“黄帝名轩。北斗，黄帝之精。母地祗之女附宝，之郊野。大电绕斗枢，星耀，感附宝，生轩，胸文曰‘黄帝子’。天地开辟，元历名、月首，甲子；冬首日、月、五星俱起牵牛。”
   * 先秦古籍记黄帝造历谓之《调历》，做法就是“拟宸极以运旋玑，揆天行而序景曜，分辰野，辨躔历。”黄帝造《调历》主要依据木星、太阳和北斗三者之间的关系来定岁；依据晷影和阴阳地气之升降来定月，依据太阳升落来定日。日星同次之月即岁星与日同次之月斗所建之辰为太岁年名，亦是斗所建之辰下有太岁也。所谓仰观俯察，就是把天象与地象综合起来制定历法，并命名为调历法。现代学者认为黄帝造《调历》只是传说，不加以重视，这是妨碍对先秦历法研究进入深一层次的重要原因。观天候气，可以说是黄帝调历法的根基。
** 春秋末期，老子站在历史的高度对现实社会进行反思，写成了《道德经》一书，标志着道家学派从此诞生。而他的思想传人，有的继承了他批判和超越的精神，形成了老庄学派；有的继承了他贵生重生的思想，形成了杨朱学派；有的继承了他经世致用的理念，形成了黄老学派。
** 黄帝先秦公认的黄老道家创始人。如儒家的创始人尧舜、墨家的创始人禹。
* 书
** <五行大义>
  
   [[http://www.gqdzs.com/read/9062.html][《五行结构论》]]

   [[http://www.360doc.com/content/13/1109/08/4530213_327834160.shtml][《五行精纪》]]

   河洛精蕴注引
** [[http://blog.sina.com.cn/s/blog_624332980100p16g.html][术数基础(上)]]
   [[http://blog.sina.com.cn/s/blog_624332980100p8a0.html][术数基础（下）]]
   [[http://www.360doc.com/content/15/0714/13/1367418_484837937.shtml][中国古代术数基础知识]]
   七政四余
   《开元占经》
* 干支与星象
  虽然没有确切的文字记载干支的来历，但我们可以根据现有资料进行推导。《易学原理与大六壬应用》一书解释如下：根据现代天文学知识，我们知道周天二十八星宿是由恒星组成的，天文学上恒星十分稳定，相对位置几千几万年甚至更长时间内都保持不变，对地的影响也是相对稳定的，而我们地球及其他太阳系的行星不断的围绕太阳公转，而整个太阳系则是相对于北极星（即紫微星）位置不变的在银河系中做螺旋运转，这就形成了因日月五星运行而造成天星之间位置关系的改变，进而改变了特定星宿对地球及地上万事万物的影响，所以古人通过夜观天象来预测及凶，《开元占经》就是古占星学著作，而七政四余和紫微斗数就是延伸出来的古星命学。
  夜观星象受时间位置气侯等诸多不利因素制约，所以人们试图寻找更为简便的方法进行占卜，地支就是在这种情况下被利用起来了。根据历法知识我们知道，月的划分是根据月亮的一次圆缺循环为标准，分为大小月，大月30天，小月29天，一年十二个月，又加以闰月补其不足。所以天文上把黄道平面划分为十二宫，以日躔过宫划分十二个月。所以古代把黄道十二宫以地支命名，十二宫又与二十八宿相对应，即子宫有女、虚、危三宿；丑宫有斗、牛二宿；寅宫有尾、箕二宿；卯宫有氐、房、心三宿；辰宫有角、亢二宿；巳宫有翼、轸二宿；午宫有柳、星、张三宿；未宫有井、鬼二宿；申宫有觜、参二宿；酉宫有胃、昴、毕三宿；戌宫有奎、娄二宿；亥宫有室、壁二宿。所以，二十八宿的天文象意是我们干支学中地支取象的象意来源，十二地支中有藏有二十八星宿，其意义也是来源于此。
  换一种方式解释，因为干支是用来计时的，我们可以把黄道十二宫平面想象成钟表的表盘，以地球为表盘中心，十二宫就是表盘的刻度指示，日月五星相当于七个指针，运行在黄道十二宫这个大表盘之上，形成一个巨大的时钟。其中，太阳就是“年”指针，地球绕太阳运行一周回到原点就是一年的时间；月亮就是“月”指针，月亮绕地球运行一周回到原点就是一个月的时间；二十四节气是跟太阳过宫有直接联系，而和月球运转没有直接关系，所以造成了历法上月令和节气的时间差，因此我们干支学的月令是根据节气而定，即跟日躔过宫相一致。我们再看两个最慢的指针，即太阳系中两个最重要的行星木星（岁星）和土星（镇星）交会的周期，需要20年,即一个运；如果两星要在同一个宫位上（比如子宫）交会的话，则需要经过60年，即一元。同理，日月五星重合在同一宫位的周期，则需要大致180年左右，即一个正元；如果把日月五星重合的位置再具体化，由夹角30度的一个宫位变为夹角12.8度的一个星宿的宿位，则需要大致540年才能重合一次，即一个大元。这个假设与实际天文学计算有出入，但如此理解起来就比较容易，也更容易把时间和空间结合起来，因为十二宫即十二地支，所代表的是空间上的十二方位；钟表的表盘代表了宇宙的能量场，即相对静止的天地的气场；日月五星的运行搅动了原本相对静止的能量场，日月五星在十二宫的位置分布，就代表了当前时间内各星对各宫的影响力大小，即当前时间空间内天体能量的分布状态，其表达形式就是甲子、乙丑、丙寅、丁卯等。
  上面我们假想的时钟只有年月指针，没有日时指针，这就需要我们把地球自转的因素加以考虑。地球自转周期为一天，即24小时，在地球自转过程中，日月五星对地球同一地点的影响时时在发生着变化，地球上同一地点相对于日月五星运转了一周；地球一天时间内公转角度向前行进约1度，也就是相对于日月五星的空间位置变化为1度，周而复始，日复一日。因此，地球上同一地点的天体能量分布以每天1度的位置而产生变化，即产生了同一地点能量分布逐日逐时变化的结果，这就是日和时的甲子、乙丑、丙寅、丁卯等等。
  地支有十二，而天干只有十个，这是为什么呢？
  首先，我们刚才的钟表模型是建立在地心说之上，而实际上我们地球和其余五星都是在围绕太阳公转，由于轨道和运转速度的不同，造成了行星运行之间相对位置的靠近和远离，也就是天文观测中的“行星逆行”，逆行在西方占星学上有着特殊的地位，传统占星师认为逆行使得行星发挥弱势的影响力。但在中国古代阴阳理论的指导下，根据五星相对于地球位置靠近和远离的这两种形式，把五星所代表的能量分为阴和阳，又根据五星影响地球的能量大小依次排序形成：甲、乙、丙、丁、戊、己、庚、辛、壬、癸十个天干。
  　天干与地支相配，多出两个地支无天干相配，形成了旬空，也叫空亡。这是由于日月五星和地球都在不停的自转和公转，搅动了原本相对静止的黄道十二宫的能量场，这就造成了地球周围能量分布的不均匀，这就相当于河流中的河水在石块下游，石块背后的地方形成的漩涡，这个漩涡的位置就是空亡。随着时间推移，日月五星位置发生了改变，漩涡的位置也随之发生改变，原来的漩涡消失，相邻的地方变成了漩涡，周而复始，循环一周，从而产生六十甲子的往复循环。
* 干支纪月
  干支纪月是由十二辰纪月发展而来，据《五行大义》中记载:大挠“采五行之情，占斗机所建，始作甲乙以名日，谓之干，作子丑以名月，谓之枝。有事于天则用日，有事于地则用月。阴阳之别，故有枝干名也。”[6]  由此知干支发明之初就是：干用于纪日，支用于纪月。
  在古代早以十二辰纪月，即为月建。在以钟表盘面理解日月五星的运行时，我们就可很清楚的看到月建是日月相会时的辰位。古代历法选冬至日且日月相会日（月朔日）为对应于“子”刻度，月针绕行一周约27天多，但此时作为太阳视运动的年针已前行了约一个刻度，月针需再前行2天多才能赶上太阳进行日月相会，这时就相会于“丑”刻度，这样日月相会日就会逐步发生在十二刻度中，以此确定月建。不同朝代年岁开始的月建地支不同。正月建寅，二月建卯，三月建辰这个是夏历。而商历是正月建丑，二月建寅，三月建卯。周历是正月建子，二月建丑，三月建寅。秦历是年开始于建亥，但仍称十月。至汉武帝改历，才复用夏正，就是正月建寅为岁首（武则天改过用周正，建子）一直沿用至今。
  干支纪月自官方到民间一直有使用！以敦煌出土的北宋《雍熙三年(986)丙午岁具注历日》（伯3403）为例，各月起始点的定义，并非历法中的朔日，而指的是各月节气，此故，二月就定义成从惊蛰(二月节)至清明(三月节)前一日，余类推。敦煌具注历以节气为各月之始的规矩，或已有相当久远的历史。但从现存各汉简残历中，均可见到以朔日作为各月月建起点的情形。
  干支纪月歌诀
  干支纪月的推算较为容易，每年的各月地支已经固定，只要推算月的天干配固定每月地支就行。有歌诀为证(寅月为正月，寅为虎，又称“五虎遁元”）：
  甲己之年丙作首，——逢年干是甲或己的年份，正月的月干从丙上起。
  乙庚之岁戊为头，——逢年干是乙或庚的年份，正月的月干从戊上起。
  丙辛必定寻庚起，——逢年干是丙或辛的年份，正月的月干从庚上起。
  丁壬壬位顺行流，——逢年干是丁或壬的年份，正月的月干从壬上起。
  更有戊癸何方觅，甲寅之上好追求。——逢年干是戊或癸的年份，正月的月干从甲上起。
* 干支纪月是干支历的一部分，主要用于风水、术数等领域中，这使得干支历一直在官方和民间都流行不衰。而事实上”正月建寅”是与北斗七星在地球上所观察的周年运动有关，与地球环绕太阳一周期的时间相同
*
   http://qrenco.de/
   #+BEGIN_SRC shell
   printf "asciinema rocks!" | curl -F-=\<- qrenco.de
   #+END_SRC

   [[https://www.zoomeye.org/][ZoomEye | 钟馗之眼 - 网络空间搜索引擎]]

   [[https://www.shodan.io/][SHODAN - Computer Search Engine]] Shodan is the world's first search engine for Internet-connected devices.

   [[http://www.tingyun.com/][听云]]

   [[https://1024tools.com/][1024程序员开发工具箱 1024tools.com]]

   [[http://mycat.io/][mycat分布式mysql中间件]]

   [[https://xiaolan.me/obfsproxy.html][使用obfsproxy混淆任意流量]]

   [[http://www.qcloud.com/event/pd][万象优图智能鉴黄]]

   [[https://bintray.com/]]
   DISTRIBUTION MADE EASY!
   Your package hosting and download center infrastructure for automated software distribution

   https://jwt.io/
   JSON Web Tokens are an open, industry standard RFC 7519 method for representing claims securely between two parties.

   JWT.IO allows you to decode, verify and generate JWT.

   [[http://rime.im/][rime输入法]]

   [[http://www.webhek.com/pathfinding][动画展示计算机迷宫路径各种搜索算法]]

   [[http://www.oschina.net/translate/what-every-web-developer-must-know-about-url-encoding][每个 Web 开发者都应该知道的关于 URL 编码的知识]]

   [[http://gomockingbird.com/][Mockingbird 在线的原型设计工具]]

   [[http://www.tutorialspoint.com/][一个学东西的网址]]

   [[http://www.kepu.net.cn/][中国科普博览]]

   [[http://www.pdtools.net][程序员开发工具网]]
   
   [[http://octave-online.net/][推举一个在线matlab(octave)]]

   [[https://love2.io/][电子书]]
   Love2.io 是一个全新的开源技术文档分享平台，我们致力于提供用户更优雅的阅读和写作体验。技术改变世界，用文档传播。

* 代码版本历史可视化
** [[http://ghv.artzub.com/][看github的]]
** http://gource.io/
** code swarm

* html5
 
  http://www.webhek.com/

  http://www.htmlfivecan.com/
* uml
  https://draw.io

  https://www.websequencediagrams.com/

  http://yuml.me/

  http://uml.riaoo.com/
  
  http://gravizo.com/
* 画
  http://sta.sh/muro/

  [[https://sketch.pixiv.net/draw][人工智能自动上色]]

* emacs
  [[https://github.com/search?utf8=%E2%9C%93&q=emacs-starter-kit][emacs-starter-kit]]
* windows 包管理器
  [[https://h404bi.com/blog/2018/05/12/talk-about-scoop-the-package-manager-for-windows-again.html][再谈谈 Scoop 这个 Windows 下的软件包管理器]]
#+BEGIN_SRC emacs-lisp
(set-language-environment 'Chinese-GB)
(set-keyboard-coding-system 'utf-8)
(set-clipboard-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-buffer-file-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-selection-coding-system 'utf-8)
(modify-coding-system-alist 'process "*" 'utf-8)
(setq default-process-coding-system '(utf-8 . utf-8))
(setq-default pathname-coding-system 'utf-8)
(set-file-name-coding-system 'utf-8)
(setq ansi-color-for-comint-mode t)
#+END_SRC
**  emacs里 replace-regexp
***  用到的几个符号是什么意思: \,
****  \# 出现的位置(第几个出现的) 解析成表达式(replace-count)
****  \#& 解析成表达式(string-to-number ...)
****  \& 匹配到的字符串 解析成表达式(match-string)
***  匹配网址的正则http://\S-+ 减号 加号什么意思
* [[http://blog.sina.com.cn/s/blog_676fb9380100rtqs.html][Web上的linux：用javascript实现虚拟机]]
* 可能和词语来源相关的东东
** 方程
中国古代代数学泰斗刘徽称一类问题是“群物总杂，各列有数，总言其实”，处理方式是 “令每行为率，二物者再程，三物者三程，皆如物数程之。并列为行，故谓之方程。” 就是说，将这些数按类一行一行的列出来，有几个未知数就排列上几行，各行称之为率，可以按比例扩大或缩小，刘徽把这样的数字方阵称为“方程”。
** 精气神
   《三命通会》
   或以三合者，如人一身之运用也。 _精乃天之元，气乃神之本，是以精为气之母，神为气之子，子母相生，精气神全而不散之为合_ 。盖谓支属人元，故以此论之。如申子辰，申乃子之母，辰乃子之子，申乃水生，子乃水旺。辰乃水气，生即产， 旺即成，库即收，有生有成有收，万物得始得终，乃自然之理，故申子辰为水局。若三字缺一则化不成局，不可以三合化局论。盖天地间道理，两则化，一阴一阳之谓也，三则化，三生万物之谓也。巳酉丑、寅午戌、亥卯未皆然。五行不言土者，四行皆赖土成局，万物皆归藏於土故也；若辰戌丑未全自作土局论。
   凡命有合，要得局为佳。假令丙丁生人见亥卯未印、巳酉丑财为得局，见寅午戌火为本局，申子辰水为官局，辰戌丑未土
   为伤局。又如丙人见巳酉丑，丁人见寅午戌为三位禄格，谓丙以已为禄，丁以午为禄，酉丑合已，寅戌合午故也。︽珞录子︾云：“禄有三会”。 《壶中子》云：“得一分三，折月中之仙桂”。此之谓也。馀仿此例。
** 不三不四
   三爻四爻居人位
* [[http://www.atool.org/][在线工具箱]]
* 代码组织
  * 数据（静态(更新)、动态(分布式?,葡萄数据，非葡萄数据，stream/log)）
    葡萄数据和缓存,葡萄数据分布式
  ** 跟据条件和模块查寻数据存取地地址,读取数据.
  *** 请求 地址引用透明
  ** 数据迁移
  * 线程
  * 锁
  * 模块(按数据，按接口)
  * 类库适配
* [[http://www.cnki.net/][中国知网]]
* [[https://frontendmasters.com/][国外的一个前端教程网站]]
* js
  [[http://ramda.cn/][Ramda 中文]] 一款实用的 JavaScript 函数式编程库。
  [[https://cn.vuejs.org/][Vue.js]] 渐进式JavaScript 框架
* lisp
  [[http://www.lambdanative.org/][移动设备上的scheme]] Practical Functional Programming.It's never been easier to deploy high-quality code on mobile and embedded targets
* java
  java enum 构造方法只能private?
  [[http://jzhihui.iteye.com/blog/1271122][影响java创建线程数量的设置]]
  [[http://www.cnblogs.com/zengkefu/p/5649407.html][ulimit 命令 并发相关]]
  java无序写返回的未调用构造器的对象引用对没个线程是同一个吗？一个线程获得了没初始化好的引用，等另一个线程调用了构造对象后，这个线程的对象是不是可以直接用了？
  Dynamic Proxy 的一个作用是阻止类型转换[[https://www.ibm.com/developerworks/library/j-jtp08305/index.html][The dynamic proxy mechanism]]
* 做个指纹密码管理app

#+begin_example
█████████████████████████████████
█████████████████████████████████
████ ▄▄▄▄▄ █ █▀█  ▀▄██ ▄▄▄▄▄ ████
████ █   █ █ ▄  ▀▀▄▀▄█ █   █ ████
████ █▄▄▄█ █▀▄█▀▄▄▀▄██ █▄▄▄█ ████
████▄▄▄▄▄▄▄█▄▀ ▀▄█▄▀ █▄▄▄▄▄▄▄████
████▄▄█▀▄ ▄▀▀▀██▄▀ █▀▀█▄▀  ▄▄████
████ █▀▀██▄ ▀█▀▄▀██  ▀████▀█▀████
████▀▀█▄  ▄  █▄▀█▄█▀▄▄ █  ▄▄█████
██████ █▄▀▄██▄▀▄▄▄ ▄▄  ██  ▀▀████
████▄▄▄███▄▄ ▀▄▄█▀▀▄ ▄▄▄ ▄ ▀▄████
████ ▄▄▄▄▄ █▀▄█ ▀▄▀▄ █▄█ ▄▀█▀████
████ █   █ █▄█▄▄ ▄ ▀   ▄▄██▀ ████
████ █▄▄▄█ █▀ ▀▀ █▄ ▄██▀█▄▀ █████
████▄▄▄▄▄▄▄█▄▄▄▄███▄█▄██▄▄█▄▄████
█████████████████████████████████
█████████████████████████████████
#+end_example
