* blog
** [[http://evi1cg.me/][一个黑客技术的blog]]
** [[http://zhan.renren.com/linuxzhouxin][Linux门徒]]
   投身Linux的海洋，拥抱真正的IT技术，使自己成为一段BOSS代码！
** [[http://calvin1978.blogcn.com/][花钱的年华]]
* great fire wall
** twister
   http://twisterio.com
   
   http://twister.net.co/
** just proxy (chrome plugin)
   http://goo.gl/0qEKSs
** http://www.dou-bi.com/
** http://fanqianghou.com/
   or
   https://s3.amazonaws.com/fanqianghou/index.html

* 不知道的东西
** Data URI scheme
   Data URI scheme是在RFC2397中定义的
** hash
   *MurmurHash* 是一种非加密型哈希函数，适用于一般的哈希检索操作。由Austin Appleby在2008年发明，并出现了多个变种，都已经发布到了公有领域(public domain)。与其它流行的哈希函数相比，对于规律性较强的key，MurmurHash的随机分布特征表现更良好。

   *Merkle Damgard*
** p2p
** 药
*** 广东凉茶
    配料：葡萄糖、鲜芦根、夏枯草、布渣叶、鸡蛋花、仙草、菊花。
*** 通窍鼻炎颗粒
    + 成分：苍耳子（炒）、防风、黄芪、白芷、辛夷、白术（炒）、薄荷。
    + 功能主治：散风消炎，宣通鼻窍。用于鼻渊，鼻塞，流涕，前额头痛；鼻炎，鼻窦炎及过敏性鼻炎。
* 书
** 
   [[http://www.tingyun.com/][听云]]

   [[http://mycat.io/][mycat分布式mysql中间件]]

   [[https://xiaolan.me/obfsproxy.html][使用obfsproxy混淆任意流量]]
* uml
  https://draw.io

  https://www.websequencediagrams.com/

  http://yuml.me/

  http://uml.riaoo.com/
* emacs
  [[https://github.com/search?utf8=%E2%9C%93&q=emacs-starter-kit][emacs-starter-kit]]
* [[http://blog.sina.com.cn/s/blog_676fb9380100rtqs.html][Web上的linux：用javascript实现虚拟机]]
* 可能和词语来源相关的东东
** 精气神
   《三命通会》
   或以三合者，如人一身之运用也。 _精乃天之元，气乃神之本，是以精为气之母，神为气之子，子母相生，精气神全而不散之为合_ 。盖谓支属人元，故以此论之。如申子辰，申乃子之母，辰乃子之子，申乃水生，子乃水旺。辰乃水气，生即产， 旺即成，库即收，有生有成有收，万物得始得终，乃自然之理，故申子辰为水局。若三字缺一则化不成局，不可以三合化局论。盖天地间道理，两则化，一阴一阳之谓也，三则化，三生万物之谓也。巳酉丑、寅午戌、亥卯未皆然。五行不言土者，四行皆赖土成局，万物皆归藏於土故也；若辰戌丑未全自作土局论。
   凡命有合，要得局为佳。假令丙丁生人见亥卯未印、巳酉丑财为得局，见寅午戌火为本局，申子辰水为官局，辰戌丑未土
   为伤局。又如丙人见巳酉丑，丁人见寅午戌为三位禄格，谓丙以已为禄，丁以午为禄，酉丑合已，寅戌合午故也。骁舐甲应缭疲骸奥挥腥会”。 《壶中子》云：“得一分三，折月中之仙桂”。此之谓也。馀仿此例。
